### ISSUE TITLE
Does not work on Windows

### ISSUE THREAD

**Issue by peter-janssen** [MeteoGroup/cassandra-embedded-for-test#2]
Unfortunately this doesn't work on windows. Out of the box I get a classnotfound exception (jackson object mapper) while running the project on the command line using maven 3.3.9 and jdk 1.8.0_92x64 on windows 7 Enterprise 64 bit. This looks like a bug in cassandra-all 3.5. When up or downgrading to 3.7 or 3.4 the surefire plugin fails with the following message: "The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?" This is due to the cassandradaemon calling System.exit on stop. Surefire doesn't handle test cases that make those calls. Circumventing this call is not a solution because the daemon is unable to stop the jvm and the test will hang-up.

This is probably insurmountable but maybe a heads-up in the readme is fine for now.

**Comment by e-karge** [comment]
I finally came around to look into this. Sorry for the delay, I had some busy weeks. After setting up a windows dev environment (Win10, jdk1.8b92-x64) I can at least say that the problem occurs during shutdown. Omitting `tearDownCassandra()` from the test is a workaround, it will leave the data files lying around though.

**Comment by e-karge** [comment]
I found that actually Cassandra itself is killing the JVM on purpose. I added some documentation about that to the README. The actual solution would be #3.
